### ISSUE TITLE
Does work with user or group mode

### ISSUE THREAD

**Issue by jpsheffield** [puppetlabs/puppetlabs-ibm_installation_manager#9]
There are 3 modes that IIM can be installed in: admin, nonAdmin and group. This module only works for admin.

I've worked out how to fix this but I'm new to puppet and git (double whammy) and I haven't worked out how to connect my local git to github through a corporate firewall yet let alone fork/pull properly, so hopefully the attached file will help - it adds a new parameter "install_mode" and then sets the correct command to call.

[init.pp.txt](https://github.com/puppetlabs/puppetlabs-ibm_installation_manager/files/81489/init.pp.txt)

**Comment by joshbeard** [comment]
If I recall correctly, this module only supported the 'admin' install mode so that the paths where the IM data was stored would be predictable.  E.g. https://github.com/puppetlabs/puppetlabs-ibm_installation_manager/blob/master/lib/puppet/provider/ibm_pkg/imcl.rb#L43

It's certainly possible to support the other installation methods, but would require a bit more work than just specifying a different installation command.  The package provider would need some additional work to handle the different installation types/locations, for example.

**Comment by jpsheffield** [comment]
Hi Josh,
Thanks, at first I didn't really understand your response as the IM "data location" can be specified as an option for any type of IM install, but there are defaults that could be assumed unless overridden by specifying extra options, however now I've looked at the code in imcl.rb I see what you mean.
The module is quite specific in terms of the way it works (and the way it works around several IBM issues), so it would be a much bigger alteration.
Might be worth mentioning in the "limitations" section of the readme though.

As a new user I think I'm guilty of trying to change the world to match my methods rather than just accepting the world works differently and I should learn from it (possibly)!
Thanks for your help

**Comment by bmjen** [comment]
@jpsheffield is this issue still pertinent? Do you mind if I close it?

**Comment by jpsheffield** [comment]
OK to close, thanks 

-----Original Message-----

**Comment by bmjen** [comment]
Thanks!
